version: '3'
services:
  training-neo4j:
    image: neo4j:${NEO4J_VERSION:-latest}
    container_name: "data-science-training-neo4j"
    volumes:
      - ./plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/admin"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*"

  training-jupyter:
    container_name: "data-science-training-jupyter"
    image: jupyter/scipy-notebook:${JUPYTER_VERSION:-latest}
    volumes:
      - ./data-science-training:/home/jovyan
    ports:
      - "8888:8888"
    
    
